"""
Gear Improvement Suggester — three-model pipeline.

Given a character's full equipment set, passive tree, and skill setup,
identifies:
1. **Which gear slot** offers the highest DPS/EHP improvement per currency
2. **What mods to target** on that slot
3. **How to acquire** the upgrade (trade vs craft, with cost estimate)

Pipeline:
    ┌──────────────────────────────┐
    │  PoB Import (XML / code)     │
    └──────────────┬───────────────┘
                   │
    ┌──────────────▼───────────────┐
    │  Slot Impact Predictor       │ → ranked slots by upgrade potential
    │  (XGBoost regression)        │
    └──────────────┬───────────────┘
                   │  (top-K slots)
    ┌──────────────▼───────────────┐
    │  Mod Recommender             │ → ranked mod changes per slot
    │  (LambdaMART / LightGBM)    │
    └──────────────┬───────────────┘
                   │
    ┌──────────────▼───────────────┐
    │  Cost Estimator              │ → trade price or craft cost
    │  (Trade API + heuristics)    │
    └──────────────────────────────┘
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import numpy as np
from loguru import logger

from ml.config import GearSuggesterConfig


# ── Data types ─────────────────────────────────────────────────────────

@dataclass
class SlotUpgrade:
    """A single recommended upgrade for one gear slot."""
    slot_name: str
    predicted_dps_delta: float
    predicted_ehp_delta: float
    confidence: float  # 0-1
    # Mod-level recommendations
    target_mods: list[ModRecommendation] = field(default_factory=list)
    # Cost
    trade_price_chaos: float = 0.0
    craft_cost_chaos: float = 0.0
    recommended_action: str = ""  # "buy" or "craft"


@dataclass
class ModRecommendation:
    """One recommended mod change on a specific item."""
    mod_text: str
    mod_type: str  # "add_prefix", "add_suffix", "upgrade_tier", "replace"
    expected_dps_gain: float
    expected_ehp_gain: float
    priority: int  # 1 = highest


# ── Model 1: Slot Impact Predictor ─────────────────────────────────────

class SlotImpactPredictor:
    """
    XGBoost model that predicts DPS/EHP delta if a given slot is upgraded
    to the "next tier" of quality.

    Training data is generated by:
    1. Taking top builds from poe.ninja
    2. For each build, systematically replacing each slot with a
       better version (T1 mods instead of T3, etc.)
    3. Computing the DPS/EHP delta using PoB engine (batch mode)
    """

    def __init__(self, cfg: GearSuggesterConfig | None = None) -> None:
        self.cfg = cfg or GearSuggesterConfig()
        self.dps_model = None
        self.ehp_model = None

    def fit(
        self,
        X: np.ndarray,
        y_dps: np.ndarray,
        y_ehp: np.ndarray,
    ) -> None:
        """
        Train both DPS and EHP impact predictors.

        Parameters
        ----------
        X : (n_samples, n_features) — gear + context features
        y_dps : (n_samples,) — DPS delta when this slot is upgraded
        y_ehp : (n_samples,) — EHP delta when this slot is upgraded
        """
        try:
            import xgboost as xgb
        except ImportError:
            raise ImportError("xgboost required: pip install xgboost")

        params = {
            "objective": "reg:squarederror",
            "max_depth": self.cfg.slot_max_depth,
            "learning_rate": self.cfg.slot_learning_rate,
            "eval_metric": "rmse",
        }

        dtrain_dps = xgb.DMatrix(X, label=y_dps)
        self.dps_model = xgb.train(
            params, dtrain_dps, num_boost_round=self.cfg.slot_n_estimators,
        )

        dtrain_ehp = xgb.DMatrix(X, label=y_ehp)
        self.ehp_model = xgb.train(
            params, dtrain_ehp, num_boost_round=self.cfg.slot_n_estimators,
        )
        logger.info("Slot impact predictor trained.")

    def predict(self, X: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """Predict DPS and EHP deltas for each slot."""
        import xgboost as xgb
        d = xgb.DMatrix(X)
        dps_pred = self.dps_model.predict(d) if self.dps_model else np.zeros(len(X))
        ehp_pred = self.ehp_model.predict(d) if self.ehp_model else np.zeros(len(X))
        return dps_pred, ehp_pred

    def save(self, dps_path: str, ehp_path: str) -> None:
        if self.dps_model:
            self.dps_model.save_model(dps_path)
        if self.ehp_model:
            self.ehp_model.save_model(ehp_path)

    def load(self, dps_path: str, ehp_path: str) -> None:
        import xgboost as xgb
        self.dps_model = xgb.Booster()
        self.dps_model.load_model(dps_path)
        self.ehp_model = xgb.Booster()
        self.ehp_model.load_model(ehp_path)


# ── Model 2: Mod Recommender ──────────────────────────────────────────

class ModRecommender:
    """
    LightGBM LambdaMART ranker that scores candidate mod changes.

    For a given slot, generates candidate improvements:
    - Add missing prefix/suffix (if open affixes)
    - Upgrade existing mod tier (T3 → T1)
    - Replace weakest mod with a stronger one

    Each candidate is scored by expected DPS/EHP delta.
    """

    def __init__(self, cfg: GearSuggesterConfig | None = None) -> None:
        self.cfg = cfg or GearSuggesterConfig()
        self.model = None

    def fit(
        self,
        X: np.ndarray,
        y: np.ndarray,
        groups: np.ndarray,
    ) -> None:
        """
        Train the ranking model.

        Parameters
        ----------
        X : (n_candidates, features) — mod candidate features
        y : (n_candidates,) — relevance labels (DPS delta normalized)
        groups : group sizes for LambdaMART (candidates per query)
        """
        try:
            import lightgbm as lgb
        except ImportError:
            raise ImportError("lightgbm required: pip install lightgbm")

        train_data = lgb.Dataset(X, label=y, group=groups)

        params = {
            "objective": "lambdarank",
            "metric": "ndcg",
            "num_leaves": self.cfg.mod_num_leaves,
            "learning_rate": self.cfg.mod_learning_rate,
            "n_estimators": self.cfg.mod_n_estimators,
            "verbose": -1,
        }

        self.model = lgb.train(params, train_data)
        logger.info("Mod recommender trained.")

    def rank_candidates(
        self,
        candidates: list[dict[str, Any]],
        features: np.ndarray,
    ) -> list[ModRecommendation]:
        """
        Rank mod candidates for a single slot.

        Parameters
        ----------
        candidates : list of dicts with "mod_text", "mod_type"
        features : (n_candidates, n_features)

        Returns
        -------
        Sorted list of ModRecommendation (highest impact first).
        """
        if self.model is None:
            # Fallback: return unsorted
            return [
                ModRecommendation(
                    mod_text=c["mod_text"],
                    mod_type=c.get("mod_type", "unknown"),
                    expected_dps_gain=0,
                    expected_ehp_gain=0,
                    priority=i + 1,
                )
                for i, c in enumerate(candidates)
            ]

        scores = self.model.predict(features)
        order = np.argsort(-scores)

        results = []
        for rank, idx in enumerate(order):
            c = candidates[idx]
            results.append(ModRecommendation(
                mod_text=c["mod_text"],
                mod_type=c.get("mod_type", "unknown"),
                expected_dps_gain=c.get("dps_gain", 0),
                expected_ehp_gain=c.get("ehp_gain", 0),
                priority=rank + 1,
            ))
        return results

    def save(self, path: str) -> None:
        if self.model:
            self.model.save_model(path)

    def load(self, path: str) -> None:
        import lightgbm as lgb
        self.model = lgb.Booster(model_file=path)


# ── Model 3: Cost Estimator ───────────────────────────────────────────

class CostEstimator:
    """
    Estimates acquisition cost for a target item.

    Two strategies:
    1. **Buy on trade**: query Trade API for items matching target mods
    2. **Craft yourself**: use Craft of Exile data / heuristics

    Returns the cheaper option with a recommendation.
    """

    def __init__(self) -> None:
        # Crafting cost heuristics (chaos equivalent per attempt)
        self.craft_costs: dict[str, float] = {
            "chaos_spam": 1.0,  # per chaos orb
            "essence_greed": 3.0,  # Screaming Essence of Greed
            "essence_wrath": 3.0,
            "fossil_pristine": 5.0,  # Pristine + resonator
            "fossil_jagged": 4.0,
            "fossil_metallic": 6.0,
            "harvest_reforge_life": 0.0,  # free from Harvest
            "harvest_reforge_fire": 0.0,
            "aisling_t4": 150.0,  # Aisling T4 unveil
            "metacraft_prefix_lock": 300.0,  # 2 divine ≈ 300c
        }

    async def estimate_trade_price(
        self,
        slot_type: str,
        target_mods: list[str],
        league: str | None = None,
    ) -> float:
        """Query trade API for estimated price."""
        from ml.data.collectors.trade_api import estimate_price

        # Build search kwargs from target mods
        kwargs: dict[str, Any] = {"item_type": slot_type}

        for mod in target_mods:
            lower = mod.lower()
            if "life" in lower:
                kwargs["min_life"] = 80
            elif "fire res" in lower:
                kwargs["min_fire_res"] = 40
            elif "cold res" in lower:
                kwargs["min_cold_res"] = 40
            elif "lightning res" in lower:
                kwargs["min_lightning_res"] = 40

        prices = await estimate_price(league=league, **kwargs)
        return prices.get("p50", 0)

    def estimate_craft_cost(
        self,
        target_mods: list[str],
        method: str = "chaos_spam",
        avg_attempts: int = 50,
    ) -> float:
        """
        Estimate crafting cost based on method and expected attempts.

        This is a rough heuristic. For accurate estimates, use Craft of Exile.
        """
        cost_per_attempt = self.craft_costs.get(method, 1.0)
        return cost_per_attempt * avg_attempts

    def recommend(
        self,
        trade_price: float,
        craft_cost: float,
    ) -> str:
        """Return 'buy' or 'craft' based on which is cheaper."""
        if trade_price <= 0:
            return "craft"
        if craft_cost <= 0:
            return "buy"
        return "buy" if trade_price <= craft_cost * 1.2 else "craft"


# ── Full pipeline ──────────────────────────────────────────────────────

class GearSuggestionPipeline:
    """
    End-to-end gear improvement suggestion.

    Usage::

        pipeline = GearSuggestionPipeline()
        pipeline.load_models("checkpoints/")
        suggestions = pipeline.suggest(build_data)
    """

    def __init__(self) -> None:
        self.slot_predictor = SlotImpactPredictor()
        self.mod_recommender = ModRecommender()
        self.cost_estimator = CostEstimator()

    def load_models(self, checkpoint_dir: str) -> None:
        """Load all sub-models from checkpoint directory."""
        from pathlib import Path
        d = Path(checkpoint_dir)
        self.slot_predictor.load(
            str(d / "slot_dps.xgb"),
            str(d / "slot_ehp.xgb"),
        )
        self.mod_recommender.load(str(d / "mod_recommender.lgb"))

    def suggest(
        self,
        gear_features: np.ndarray,
        build_context: np.ndarray,
        top_k_slots: int = 3,
    ) -> list[SlotUpgrade]:
        """
        Generate improvement suggestions.

        Parameters
        ----------
        gear_features : (num_slots, features_per_slot)
        build_context : (context_dim,)
        top_k_slots : how many slots to return suggestions for

        Returns
        -------
        list[SlotUpgrade] — top-K slots with mod recommendations
        """
        from ml.data.processing.feature_engineering import SLOT_NAMES

        # Predict impact per slot
        n_slots = gear_features.shape[0]
        # Flatten each slot's features + context → one row per slot
        X = np.hstack([
            gear_features,
            np.tile(build_context, (n_slots, 1)),
        ])

        dps_deltas, ehp_deltas = self.slot_predictor.predict(X)

        # Rank slots by combined delta
        combined = 0.6 * dps_deltas + 0.4 * ehp_deltas
        top_indices = np.argsort(-combined)[:top_k_slots]

        suggestions = []
        for idx in top_indices:
            slot_name = SLOT_NAMES[idx] if idx < len(SLOT_NAMES) else f"Slot {idx}"
            upgrade = SlotUpgrade(
                slot_name=slot_name,
                predicted_dps_delta=float(dps_deltas[idx]),
                predicted_ehp_delta=float(ehp_deltas[idx]),
                confidence=float(min(1.0, abs(combined[idx]) / max(combined.max(), 1))),
            )
            suggestions.append(upgrade)

        return suggestions
